# Generated by Django 5.0.1 on 2024-02-29 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_user_role_alter_user_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.ImageField(
                default="profile.jpg", upload_to="media/profilepicture"
            ),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pcategory",
                    models.CharField(
                        choices=[
                            ("Men", "Men"),
                            ("Women", "Women"),
                            ("Child", "Child"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "psize",
                    models.CharField(
                        choices=[
                            ("S", "S"),
                            ("XS", "XS"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pbrand",
                    models.CharField(
                        choices=[
                            ("Levis", "Levis"),
                            ("Roadstar", "Roadstar"),
                            ("Nike", "Nike"),
                            ("Supreme", "Supreme"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.PositiveBigIntegerField()),
                ("desc", models.TextField()),
                ("picture", models.ImageField(default="", upload_to="P_Picture")),
                ("pname", models.CharField(max_length=30)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
                    ),
                ),
            ],
        ),
    ]
