# Generated by Django 5.0.1 on 2024-04-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_order_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="picture",
        ),
    ]
