# Generated by Django 5.0.1 on 2024-04-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_remove_order_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="pincode",
            field=models.CharField(max_length=8),
        ),
    ]
