# Generated by Django 5.0.1 on 2024-04-20 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_alter_order_pincode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="city",
        ),
        migrations.RemoveField(
            model_name="order",
            name="state",
        ),
    ]
